/* 1. */
SELECT COUNT(DISTINCT JOB_ID) FROM `employees`;

/* 2. */
SELECT SUM(SALARY) FROM `employees`;

/* 3. */
SELECT MIN(SALARY) FROM `employees`;

/* 4. */
SELECT MAX(SALARY) FROM `employees` WHERE JOB_ID="IT_PROG";

/* 5. */
SELECT AVG(SALARY), COUNT(*) FROM `employees` WHERE DEPARTMENT_ID=90;

/* 6. */
SELECT MAX(SALARY), MIN(SALARY), SUM(SALARY), AVG(SALARY) FROM `employees`;

/* 7. */
SELECT JOB_ID, COUNT(*) FROM `employees` GROUP BY JOB_ID;

/* 8. */
SELECT MAX(SALARY) - MIN(SALARY) FROM `employees`;

/* 9. */
SELECT MANAGER_ID, MIN(SALARY) FROM employees GROUP BY MANAGER_ID;

/* 10. */
SELECT DEPARTMENT_ID, SUM(SALARY) FROM `employees` GROUP BY DEPARTMENT_ID;

/* 11. */
SELECT JOB_ID, AVG(SALARY) FROM `employees` WHERE JOB_ID != "IT_PROG" GROUP BY JOB_ID;

/* 12. */
SELECT JOB_ID, MAX(SALARY), MIN(SALARY), SUM(SALARY), AVG(SALARY) FROM `employees` WHERE DEPARTMENT_ID = 90 GROUP BY JOB_ID;

/* 13. */
SELECT JOB_ID, MAX(JOB_ID) FROM `employees` GROUP BY JOB_ID HAVING MAX(SALARY) >= 4000;

/* 14. */
SELECT DEPARTMENT_ID, AVG(SALARY) FROM `employees` GROUP BY DEPARTMENT_ID HAVING COUNT(*) > 10;