/* 1. */
SELECT FIRST_NAME, LAST_NAME, SALARY FROM employees WHERE SALARY<10000 OR SALARY>15000;
 
/* 2. */
SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_ID FROM employees WHERE DEPARTMENT_ID=30 OR DEPARTMENT_ID=100 ORDER BY DEPARTMENT_ID;
 
/* 3. */
SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_ID, SALARY FROM employees WHERE DEPARTMENT_ID=30 OR DEPARTMENT_ID=100 AND SALARY<10000 OR SALARY>15000;
 
/* 4. */
SELECT FIRST_NAME, LAST_NAME, HIRE_DATE FROM employees WHERE YEAR(HIRE_DATE)=1987;
 
/* 5. */
SELECT FIRST_NAME FROM employees WHERE FIRST_NAME LIKE '%b%' AND FIRST_NAME LIKE '%c%';
 
/* 6. */
SELECT LAST_NAME, JOB_ID, SALARY FROM employees WHERE JOB_ID='ID_PROG' OR JOB_ID='ST_CLERK' AND SALARY!=4500 AND SALARY!=10000 AND SALARY!=15000;
 
/* 7. */
SELECT LAST_NAME FROM employees WHERE LAST_NAME LIKE '______';
 
/* 8. */
SELECT LAST_NAME FROM employees WHERE LAST_NAME LIKE '__e%';
 
/* 9. */
SELECT DISTINCT JOB_ID FROM employees;
 
/* 10. */
SELECT DISTINCT FIRST_NAME, LAST_NAME, SALARY, SALARY*0.15 AS PF FROM employees;
 
/* 11. */
SELECT * FROM employees WHERE LAST_NAME='Blake' OR LAST_NAME='Scott' OR LAST_NAME='King' OR LAST_NAME='Ford';